# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: autoupdate

on: push
#on:
#  schedule:
#    - cron: '0 0 * * *' # Daily at midnight
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: importing
        run: |
          python -m astrocats setup
          python -m astrocats cataclysmic import
      - name: generating catalog
        run: |
          python -m astrocats.scripts.webcat -c cv
          python -m astrocats.scripts.bibliocat -c cv
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "astrocats/cataclysmic/output/catalog.json,astrocats/cataclysmic/output/catalog.min.json,
          astrocats/cataclysmic/output/biblio.json"
          target: "public_html"